from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import sys
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

ROOT = Path.home() / "Desktop/paper set/PQC_V2X_Security_Conditioned/numerical_experiments"
SRC = ROOT / "02_src"
CFGDIR = ROOT / "01_config"
RESULTS = ROOT / "04_results"
TOL = 1.0e-10


def atomic_write(path: Path, text: str) -> None:
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(text, encoding="utf-8")
    tmp.replace(path)


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for block in iter(lambda: f.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    fields: list[str] = []
    seen = set()
    for row in rows:
        for key in row:
            if key not in seen:
                seen.add(key)
                fields.append(key)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for row in rows:
            w.writerow({k: row.get(k, "") for k in fields})


def cells_intersecting_interval(axis: np.ndarray, lo: float, hi: float) -> np.ndarray:
    axis = np.asarray(axis, dtype=float)
    lo, hi = float(min(lo, hi)), float(max(lo, hi))
    if hi < axis[0] - 1e-12 or lo > axis[-1] + 1e-12:
        return np.empty(0, dtype=np.int64)
    lo = max(lo, float(axis[0]))
    hi = min(hi, float(axis[-1]))
    left = axis[:-1]
    right = axis[1:]
    mask = (right >= lo - 1e-12) & (left <= hi + 1e-12)
    return np.flatnonzero(mask).astype(np.int64)


def scalar_cell_index(axis: np.ndarray, x: float) -> tuple[int, bool]:
    axis = np.asarray(axis, dtype=float)
    valid = bool(x >= axis[0] - 1e-12 and x <= axis[-1] + 1e-12)
    idx = int(np.searchsorted(axis, x, side="right") - 1)
    idx = int(np.clip(idx, 0, len(axis) - 2))
    return idx, valid


def pending_descriptor_envelope(*, age: float, bar_a: float, bar_u: float,
                                q: int, R: int, Ts: float, J: float,
                                b0, p3a: dict, p2b: dict) -> dict:
    """Conservative pending descriptor envelope for the diagnostic countdown.

    The pending candidate is generated (R-q)*Ts before the current sample.
    Relative to the generation time of the currently adopted tuple, the elapsed
    propagation time is age - pending_age.  The acceleration interval uses the
    model's existing certified lower predictor plus the symmetric uncertainty
    structure declared in the manuscript.  The command interval is generated by
    the declared slew-rate bound.  This deliberately over-approximates omitted
    correlations, which is conservative for robust adoption analysis.
    """
    pending_age = (R - q) * Ts
    elapsed = float(age - pending_age)
    if elapsed < -1e-10:
        return {"valid": False, "reason": "PENDING_GENERATION_PRECEDES_ADOPTED_GENERATION"}
    elapsed = max(elapsed, 0.0)
    tau = float(p3a.get("predecessor", {}).get("tau", p2b["predecessor"]["tau"]))
    nominal_a = float(bar_u + (bar_a - bar_u) * math.exp(-elapsed / tau))
    lower = float(b0.predecessor_acceleration_lower(
        np.asarray([elapsed]), np.asarray([bar_a]), np.asarray([bar_u]),
        J, p3a, p2b,
    )[0])
    radius = max(nominal_a - lower, 0.0)
    a_lo = lower
    a_hi = nominal_a + radius
    sd = p2b["state_domain"]
    a_lo = max(float(sd["a_p_min"]), a_lo)
    a_hi = min(float(sd["a_p_max"]), a_hi)
    pred = p3a.get("predecessor", {})
    u_min = float(pred.get("command_min", sd.get("a_p_min", -8.0)))
    u_max = float(pred.get("command_max", sd.get("a_p_max", 3.0)))
    u_lo = max(u_min, float(bar_u - J * elapsed))
    u_hi = min(u_max, float(bar_u + J * elapsed))
    if a_lo > a_hi + 1e-12 or u_lo > u_hi + 1e-12:
        return {"valid": False, "reason": "EMPTY_DESCRIPTOR_ENVELOPE"}
    return {
        "valid": True,
        "pending_age_before_interval_s": float(pending_age),
        "candidate_age_if_completion_s": float(pending_age + Ts),
        "elapsed_from_adopted_generation_to_pending_generation_s": float(elapsed),
        "a_nominal": nominal_a,
        "a_lower": float(a_lo),
        "a_upper": float(a_hi),
        "u_lower": float(u_lo),
        "u_upper": float(u_hi),
    }


def descriptor_cell_indices(lookup_axes, fixed_values: tuple[float, float, float, float],
                            env: dict) -> tuple[np.ndarray, bool]:
    """Enumerate every 6-D lookup cell intersecting the chi rectangle.

    fixed_values=(v_f_next,v_p_next,a_f_next,candidate_age).  bar_a and bar_u
    range over the full pending descriptor envelope.  Taking the maximum of the
    already corner-maxed Bellman values over all intersected cells is a rigorous
    enclosure of the finite lookup representation for this rectangle.
    """
    vf1, vp1, af1, age1 = fixed_values
    fixed = []
    for axis, x in zip((lookup_axes[0], lookup_axes[1], lookup_axes[2]), (vf1, vp1, af1)):
        j, ok = scalar_cell_index(axis, x)
        if not ok:
            return np.empty(0, dtype=np.int64), False
        fixed.append(j)
    ba_cells = cells_intersecting_interval(lookup_axes[3], env["a_lower"], env["a_upper"])
    bu_cells = cells_intersecting_interval(lookup_axes[4], env["u_lower"], env["u_upper"])
    age_cell, age_ok = scalar_cell_index(lookup_axes[5], age1)
    if not age_ok or len(ba_cells) == 0 or len(bu_cells) == 0:
        return np.empty(0, dtype=np.int64), False
    shape = tuple(len(a) - 1 for a in lookup_axes)
    inds = []
    for iba in ba_cells:
        for ibu in bu_cells:
            inds.append(np.ravel_multi_index(
                (fixed[0], fixed[1], fixed[2], int(iba), int(ibu), age_cell), shape
            ))
    return np.asarray(sorted(set(int(x) for x in inds)), dtype=np.int64), True


def robust_requirement(*, i: int, q: int, action: float, data: dict,
                       h_flat: np.ndarray, R: int, r3, b0, r9e) -> dict:
    cfg, p1, p2b, p3a = data["eval_cfg"], data["p1"], data["p2b"], data["p3a"]
    vf, vp, af, bar_a, bar_u, age = [np.asarray(x, float) for x in data["eval_flat"]]
    Ts = float(data["Ts"])
    J = float(cfg["information_contract"]["slew_rate"])
    nt = int(cfg["one_step"]["trajectory_points"])
    times = np.linspace(0.0, Ts, nt)
    tau = float(p2b["follower"]["tau"])
    w = float(p1["uncertainty"]["follower_actuation_abs"])
    sd = p2b["state_domain"]
    speed_bound = float(sd["v_f_max"]) + float(sd["v_p_max"])
    lips = 0.5 * speed_bound * (Ts / (nt - 1))

    sl = slice(i, i + 1)
    ap_lower = b0.predecessor_acceleration_lower(
        age[sl], bar_a[sl], bar_u[sl], J, p3a, p2b
    )
    Pp, Vp, Ap, Up, _ = r3.predecessor_motion_with_stop(
        vp[sl], ap_lower, bar_u[sl], age[sl], times, J, p3a
    )
    Pf, Vf, Af, _ = r9e.generalized_follower_motion(
        vf[sl], af[sl], float(action), times, tau, w
    )
    closing = Pf - Pp
    step_loss = float(max(np.max(closing, axis=1)[0] + lips, 0.0))
    closing_end = float(Pf[0, -1] - Pp[0, -1])

    axes = data["lookup_axes"]
    defer_vals = [
        Vf[:, -1], Vp[:, -1], Af[:, -1], bar_a[sl], bar_u[sl], age[sl] + Ts
    ]
    didx, dvalid = r3.locate_cells(axes, defer_vals)
    if not bool(dvalid[0]):
        return {"valid": False, "reason": "DEFER_OUTSIDE_LOOKUP"}

    env = pending_descriptor_envelope(
        age=float(age[i]), bar_a=float(bar_a[i]), bar_u=float(bar_u[i]),
        q=int(q), R=int(R), Ts=Ts, J=J, b0=b0, p3a=p3a, p2b=p2b,
    )
    if not env.get("valid", False):
        return {"valid": False, "reason": env.get("reason", "INVALID_CHI")}

    c_age = float(env["candidate_age_if_completion_s"])
    c_cells, cvalid = descriptor_cell_indices(
        axes,
        (float(Vf[0, -1]), float(Vp[0, -1]), float(Af[0, -1]), c_age),
        env,
    )
    if not cvalid:
        return {"valid": False, "reason": "CHI_ENVELOPE_OUTSIDE_LOOKUP"}

    h = h_flat.reshape(data["lookup_shape"] + (R,))
    cmax = r3.cell_corner_max(h)
    cell_flat = [cmax[..., qq].reshape(-1) for qq in range(R)]

    # Completion output reveals authenticated content.  The preselected causal
    # adoption map may choose adopt/hold as a function of that output.  Since
    # hold is independent of chi, max_chi min(adopt(chi),hold) equals
    # min(max_chi adopt(chi), hold).
    robust_adopt = float(np.max(cell_flat[R - 1][c_cells]))
    hold = float(cell_flat[R - 1][int(didx[0])])
    completion = min(robust_adopt, hold)
    future = completion
    if q > 1:
        defer = float(cell_flat[q - 2][int(didx[0])])
        future = max(completion, defer)
    req = max(step_loss, closing_end + future, 0.0)
    projected = min(float(data["eval_fallback"][i]), req)
    return {
        "valid": bool(math.isfinite(projected)),
        "projected_required_gap_m": float(projected),
        "raw_required_gap_m": float(req),
        "step_loss_upper_m": step_loss,
        "closing_end_m": closing_end,
        "robust_adopt_future_m": robust_adopt,
        "hold_future_m": hold,
        "descriptor_cells": int(len(c_cells)),
        **env,
    }


def self_test() -> None:
    axis = np.asarray([0.0, 1.0, 2.0, 3.0])
    assert np.array_equal(cells_intersecting_interval(axis, 0.2, 1.8), np.asarray([0, 1]))
    assert np.array_equal(cells_intersecting_interval(axis, 1.0, 1.0), np.asarray([0, 1]))
    assert len(cells_intersecting_interval(axis, -2.0, -1.0)) == 0
    j, ok = scalar_cell_index(axis, 3.0)
    assert ok and j == 2
    # Causal identity used by robust completion branch.
    xs = [1.0, 4.0, 2.0]
    h = 2.5
    assert abs(max(min(x, h) for x in xs) - min(max(xs), h)) < 1e-12
    print("R9F_INTERNAL_SELF_TEST=PASS")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--self-test", action="store_true")
    ap.add_argument("--chunk-size", type=int, default=4096)
    args = ap.parse_args()
    if args.self_test:
        self_test()
        return 0

    sys.path.insert(0, str(SRC))
    import p3b1_augmented_fixed_point_v1_r3 as r3
    import p3b0_freshness_service_audit_v1 as b0
    import p3b1_r5_refinement_attribution as r5
    import p3b1_r6_continuation_halo as r6
    import p3b1_r7_frozen_halo_fixed_point as r7
    import p3b1_r9c_targeted_history_gate as r9c
    import p3b1_r9d_timestamped_service as r9d
    import p3b1_r9e_service_contract_general_action as r9e

    upstream = RESULTS / "P3B1_R9E_LATEST.json"
    e = json.loads(upstream.read_text(encoding="utf-8"))
    if e.get("status") != "PASS":
        raise RuntimeError("R9F_R9E_UPSTREAM_NOT_PASS")
    if e.get("classification") != "PENDING_DESCRIPTOR_MATERIAL_ON_TIMESTAMPED_Q_WITNESSES":
        raise RuntimeError("R9F_UNEXPECTED_R9E_CLASSIFICATION=" + str(e.get("classification")))

    data = r9d.reconstruct_timestamped_geometry(r3, r5, r6, r7, r9c)
    profile = "diagnostic_fast"
    R = r7.service_horizon(profile, data["p1"]["diagnostic_service_profiles"][profile])
    Ts = float(data["Ts"])
    semantic_mask, semantic_diag = r9d.timestamped_semantic_mask(
        np.asarray(data["eval_flat"][-1], float), R, Ts
    )

    print("=== P3-B1-R9-F SPARSE EXPLICIT-CHI ENVELOPE SERVICE GRAPH ===", flush=True)
    print(f"PROFILE={profile} R={R} Ts={Ts:.12g}", flush=True)
    print("CHI_MODEL=AXIS_ALIGNED_REACHABLE_ENVELOPE_FROM_STALE_UNCERTAINTY_AND_SLEW", flush=True)
    print("PSI_MODEL=COMPLETION_TERMINATES_CURRENT_CANDIDATE_AND_RESTARTS_DIAGNOSTIC_CYCLE", flush=True)
    print("CAUSAL_COMPLETION_QUANTIFIER=MAX_CHI_MIN_ADOPT_HOLD", flush=True)
    pending_age_by_q = {q: float((R-q)*Ts) for q in range(1, R+1)}
    matched_generation_time_available = len(set(round(v, 12) for v in pending_age_by_q.values())) < len(pending_age_by_q)
    print("COUNTDOWN_PENDING_AGE_BY_Q=" + ",".join(f"q{q}:{pending_age_by_q[q]:.12g}" for q in sorted(pending_age_by_q)), flush=True)
    print("COUNTDOWN_Q_DETERMINES_PENDING_GENERATION_AGE=YES", flush=True)
    print("MATCHED_CHI_ACROSS_DISTINCT_Q_AVAILABLE=" + ("YES" if matched_generation_time_available else "NO"), flush=True)
    print("DEPLOYMENT_PROTOCOL_CERTIFIED=NO", flush=True)
    print("CONTINUOUS_STATE_SEPARATION_CERTIFIED=NO", flush=True)

    frozen_actions = [-3.0, -2.0, -1.0]
    action_grid = [-6.0, -5.0, -4.0, -3.0, -2.5, -2.0, -1.5, -1.0,
                   -0.5, 0.0, 0.5, 1.0, 1.5, 2.0, 2.5]

    print("R9F_STAGE_START=recompute_timestamped_continuation", flush=True)
    cfg_frozen, td = r9d.build_timestamped_transitions(
        data, frozen_actions, R, r3, b0, chunk_size=args.chunk_size
    )
    sol = r9d.solve_timestamped_causal(
        R, cfg_frozen, data["eval_idx"], data["lookup_shape"],
        data["lookup_fallback"], data["eval_fallback"], td, r3,
        label="r9f_timestamped_continuation",
    )
    if not sol.converged:
        raise RuntimeError("R9F_TIMESTAMPED_CONTINUATION_NOT_CONVERGED")
    widx, old_spans = r9d.qdep_indices(sol.h_flat, data["eval_idx"], semantic_mask)
    expected = int(e["metrics"]["r9d_witness_count"])
    if len(widx) != expected:
        raise RuntimeError(f"R9F_R9D_WITNESS_REPRO_FAIL expected={expected} actual={len(widx)}")
    print(f"R9F_R9D_WITNESS_REPRO=PASS count={len(widx)}", flush=True)

    # General motion regression inherited from R9-E remains a hard gate.
    vf, vp, af, ba, bu, age = [np.asarray(x, float) for x in data["eval_flat"]]
    sample_idx = np.linspace(0, len(vf) - 1, min(257, len(vf)), dtype=int)
    times = np.linspace(0.0, Ts, int(data["eval_cfg"]["one_step"]["trajectory_points"]))
    tau = float(data["p2b"]["follower"]["tau"])
    w = float(data["p1"]["uncertainty"]["follower_actuation_abs"])
    max_reg = 0.0
    for a in frozen_actions:
        P0, V0, A0 = r3.follower_motion(vf[sample_idx], af[sample_idx], a, times, data["p1"], data["p2b"])
        P1, V1, A1, _ = r9e.generalized_follower_motion(vf[sample_idx], af[sample_idx], a, times, tau, w)
        max_reg = max(max_reg, float(np.max(np.abs(P0-P1))), float(np.max(np.abs(V0-V1))), float(np.max(np.abs(A0-A1))))
    if max_reg > 1e-11:
        raise RuntimeError(f"R9F_GENERAL_PROPAGATOR_REGRESSION_FAIL max_error={max_reg}")
    print(f"R9F_GENERAL_PROPAGATOR_REGRESSION=PASS max_error={max_reg:.3e}", flush=True)

    service_rows = []
    witness_rows = []
    robust_frozen_qdep = 0
    robust_full_qdep = 0
    max_frozen_span = 0.0
    max_full_span = 0.0
    full_action_material_pairs = 0
    max_action_improvement = 0.0
    invalid_trials = 0
    max_descriptor_cells = 0
    envelope_defer_consistency_fail = 0

    print("R9F_STAGE_START=sparse_chi_graph_witness_audit", flush=True)
    for count, i in enumerate(widx, start=1):
        frozen_by_q = {}
        full_by_q = {}
        for q in range(1, R + 1):
            if not semantic_mask[i, q - 1]:
                continue
            # Build and record chi envelope / graph semantics.
            env = pending_descriptor_envelope(
                age=float(age[i]), bar_a=float(ba[i]), bar_u=float(bu[i]),
                q=q, R=R, Ts=Ts,
                J=float(data["eval_cfg"]["information_contract"]["slew_rate"]),
                b0=b0, p3a=data["p3a"], p2b=data["p2b"],
            )
            if not env.get("valid", False):
                invalid_trials += 1
                continue
            # Defer consistency: q -> q-1, age -> age+Ts must reconstruct same pending chi.
            if q > 1:
                env2 = pending_descriptor_envelope(
                    age=float(age[i] + Ts), bar_a=float(ba[i]), bar_u=float(bu[i]),
                    q=q-1, R=R, Ts=Ts,
                    J=float(data["eval_cfg"]["information_contract"]["slew_rate"]),
                    b0=b0, p3a=data["p3a"], p2b=data["p2b"],
                )
                for key in ("a_lower", "a_upper", "u_lower", "u_upper"):
                    if (not env2.get("valid", False)) or abs(float(env[key]) - float(env2[key])) > 1e-10:
                        envelope_defer_consistency_fail += 1
                        break

            frozen_vals = []
            full_vals = []
            best_frozen_action = None
            best_full_action = None
            for action in action_grid:
                try:
                    rr = robust_requirement(
                        i=int(i), q=q, action=float(action), data=data,
                        h_flat=sol.h_flat, R=R, r3=r3, b0=b0, r9e=r9e,
                    )
                except Exception:
                    rr = {"valid": False, "reason": "EXCEPTION"}
                if not rr.get("valid", False):
                    invalid_trials += 1
                    continue
                max_descriptor_cells = max(max_descriptor_cells, int(rr["descriptor_cells"]))
                full_vals.append((float(rr["projected_required_gap_m"]), float(action), rr))
                if action in frozen_actions:
                    frozen_vals.append((float(rr["projected_required_gap_m"]), float(action), rr))
            if not frozen_vals or not full_vals:
                continue
            fbest = min(frozen_vals, key=lambda z: z[0])
            abest = min(full_vals, key=lambda z: z[0])
            frozen_by_q[q] = fbest[0]
            full_by_q[q] = abest[0]
            improve = fbest[0] - abest[0]
            if improve > TOL:
                full_action_material_pairs += 1
                max_action_improvement = max(max_action_improvement, improve)
            best_frozen_action = fbest[1]
            best_full_action = abest[1]
            service_rows.append({
                "node_index": int(i), "q": q,
                "adopted_age_s": float(age[i]),
                "pending_age_before_interval_s": env["pending_age_before_interval_s"],
                "candidate_age_if_completion_s": env["candidate_age_if_completion_s"],
                "chi_a_lower": env["a_lower"], "chi_a_upper": env["a_upper"],
                "chi_u_lower": env["u_lower"], "chi_u_upper": env["u_upper"],
                "event_defer_q_next": q-1 if q > 1 else "NOT_ADMITTED",
                "event_completion_q_next": R,
                "completion_adoption_choice": "ADOPT_OR_HOLD_AFTER_OBSERVING_ELIGIBLE_CONTENT",
                "psi_rule": "TERMINATE_CURRENT_AND_RESTART_CYCLE",
                "frozen_best_required_gap_m": fbest[0],
                "frozen_best_action": best_frozen_action,
                "full_grid_best_required_gap_m": abest[0],
                "full_grid_best_action": best_full_action,
                "full_minus_frozen_improvement_m": improve,
                "descriptor_cells_best_full": int(abest[2]["descriptor_cells"]),
            })

        if len(frozen_by_q) >= 2:
            span = max(frozen_by_q.values()) - min(frozen_by_q.values())
            max_frozen_span = max(max_frozen_span, span)
            if span > TOL:
                robust_frozen_qdep += 1
        else:
            span = 0.0
        if len(full_by_q) >= 2:
            span_full = max(full_by_q.values()) - min(full_by_q.values())
            max_full_span = max(max_full_span, span_full)
            if span_full > TOL:
                robust_full_qdep += 1
        else:
            span_full = 0.0
        witness_rows.append({
            "node_index": int(i),
            "v_f": float(vf[i]), "v_p": float(vp[i]), "a_f": float(af[i]),
            "bar_a": float(ba[i]), "bar_u": float(bu[i]), "age": float(age[i]),
            "r9d_q_span_m": float(old_spans[i]),
            "robust_chi_frozen_q_span_m": float(span),
            "robust_chi_full_action_q_span_m": float(span_full),
            "robust_chi_frozen_qdep": bool(span > TOL),
            "robust_chi_full_action_qdep": bool(span_full > TOL),
        })
        if count == 1 or count % 8 == 0 or count == len(widx):
            print(f"R9F_PROGRESS witnesses={count}/{len(widx)}", flush=True)

    if envelope_defer_consistency_fail:
        raise RuntimeError(f"R9F_CHI_DEFER_CONSISTENCY_FAIL count={envelope_defer_consistency_fail}")

    if not matched_generation_time_available:
        classification = "COUNTDOWN_Q_CONFOUNDS_SERVICE_PROGRESS_WITH_PENDING_MESSAGE_HISTORY"
        next_action = "R9G_BUILD_MATCHED_CHI_BRANCHING_SERVICE_AUTOMATON_STAGE_TIMING_CONTENT"
    elif robust_frozen_qdep == 0:
        classification = "Q_LAYER_REMOVED_BY_ROBUST_PENDING_DESCRIPTOR_ENVELOPE"
        next_action = "R9G_REBUILD_PROTOCOL_SPECIFIC_SERVICE_STATE_BEFORE_ANY_CONTINUOUS_PROMOTION"
    elif robust_full_qdep == 0 and robust_frozen_qdep > 0:
        classification = "COARSE_GENERAL_ACTION_REMOVES_ROBUST_CHI_Q_LAYER"
        next_action = "R9G_INTERVAL_ACTION_COVER_WITH_EXPLICIT_CHI_SERVICE_GRAPH"
    else:
        classification = "MATCHED_CHI_ROBUST_Q_LAYER_PERSISTS_ON_DIAGNOSTIC_SERVICE_GRAPH"
        next_action = "R9G_SPARSE_AUGMENTED_FIXED_POINT_GFP_PLUS_INTERVAL_ACTION_INNER_OUTER_CERTIFICATES"

    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    result_json = RESULTS / f"P3B1_R9F_RESULT_{stamp}.json"
    latest_json = RESULTS / "P3B1_R9F_LATEST.json"
    graph_csv = RESULTS / f"P3B1_R9F_SPARSE_SERVICE_GRAPH_{stamp}.csv"
    witness_csv = RESULTS / f"P3B1_R9F_ROBUST_CHI_WITNESSES_{stamp}.csv"
    manifest = RESULTS / f"P3B1_R9F_MANIFEST_{stamp}.sha256"
    write_csv(graph_csv, service_rows)
    write_csv(witness_csv, witness_rows)

    out = {
        "schema": "SCV_P3B1_R9F_SPARSE_CHI_ENVELOPE_GRAPH_V1",
        "status": "PASS",
        "timestamp_utc": stamp,
        "classification": classification,
        "next_action": next_action,
        "continuous_state_separation_certified": False,
        "markov_sufficiency_certified": False,
        "diagnostic_service_contract": {
            "profile": profile,
            "R": R,
            "chi_representation": "axis-aligned reachable envelope in pending acceleration/command content",
            "psi": "completion terminates current candidate and restarts diagnostic cycle",
            "defer_carries_same_pending_descriptor": True,
            "deployment_protocol_certified": False,
            "countdown_pending_age_by_q_seconds": {str(k): v for k, v in pending_age_by_q.items()},
            "countdown_q_determines_pending_generation_age": True,
            "matched_chi_across_distinct_q_available": bool(matched_generation_time_available),
        },
        "theory_status": {
            "core_viability_fixed_point_definition_retained": True,
            "causal_output_dependent_adoption_retained": True,
            "pending_descriptor_single_point_proxy_retired": True,
            "chi_envelope_robustified": True,
            "full_augmented_fixed_point_with_chi_not_yet_solved": True,
            "continuous_action_interval_certificate": False,
            "maximal_gfp_inner_outer_certificate": False,
        },
        "metrics": {
            "upstream_r9d_q_witnesses": int(len(widx)),
            "robust_chi_frozen_qdep_nodes": int(robust_frozen_qdep),
            "robust_chi_full_action_qdep_nodes": int(robust_full_qdep),
            "max_robust_chi_frozen_q_span_m": float(max_frozen_span),
            "max_robust_chi_full_action_q_span_m": float(max_full_span),
            "coarse_full_action_material_state_q_pairs": int(full_action_material_pairs),
            "max_coarse_action_improvement_m": float(max_action_improvement),
            "max_descriptor_lookup_cells": int(max_descriptor_cells),
            "invalid_trials": int(invalid_trials),
            "general_propagator_regression_max_error": float(max_reg),
            "reachable_qage_pairs": int(semantic_diag["reachable_qage_pairs"]),
        },
        "gates": {
            "r9e_upstream_pass": True,
            "r9d_witness_reproduction": int(len(widx)) == expected,
            "general_propagator_regression": bool(max_reg <= 1e-11),
            "chi_defer_invariance": envelope_defer_consistency_fail == 0,
            "descriptor_set_not_single_point": True,
            "deployment_protocol_markov_sufficiency": False,
            "matched_chi_progress_comparison": bool(matched_generation_time_available),
        },
        "artifacts": {
            "sparse_service_graph_csv": str(graph_csv),
            "robust_chi_witness_csv": str(witness_csv),
        },
    }
    text = json.dumps(out, indent=2, sort_keys=True)
    atomic_write(result_json, text)
    atomic_write(latest_json, text)
    mfiles = [Path(__file__), result_json, graph_csv, witness_csv, upstream,
              RESULTS / "P3B1_R9D_LATEST.json"]
    atomic_write(manifest, "".join(f"{sha256_file(p)}  {p}\n" for p in mfiles if p.exists()))

    print("=== R9-F DECISION ===", flush=True)
    print(
        f"R9F_ROBUST_CHI frozen_qdep={robust_frozen_qdep} "
        f"full_action_qdep={robust_full_qdep} "
        f"max_frozen_qspan_m={max_frozen_span:.12g} "
        f"max_full_qspan_m={max_full_span:.12g}", flush=True,
    )
    print(
        f"R9F_GENERAL_ACTION material_pairs={full_action_material_pairs} "
        f"max_improvement_m={max_action_improvement:.12g} "
        f"invalid_trials={invalid_trials}", flush=True,
    )
    print("R9F_CHI_DEFER_INVARIANCE=PASS", flush=True)
    print("MATCHED_CHI_PROGRESS_COMPARISON=" + ("AVAILABLE" if matched_generation_time_available else "NOT_AVAILABLE_IN_COUNTDOWN_MODEL"), flush=True)
    print("R9F_EXECUTION=PASS", flush=True)
    print(f"R9F_CLASSIFICATION={classification}", flush=True)
    print("CONTINUOUS_STATE_SEPARATION_CERTIFIED=NO", flush=True)
    print("MARKOV_SUFFICIENCY_CERTIFIED=NO", flush=True)
    print(f"R9F_NEXT_ACTION={next_action}", flush=True)
    print(f"RESULT_JSON={result_json}", flush=True)
    print(f"MANIFEST={manifest}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
